target 'Example-iOS_ObjC' do
  platform :ios, '9.0'

  # AppAuth Pod
  # In production, just use `pod 'AppAuth'` without the path reference.
  pod 'AppAuth', :path => '../../'
  pod 'JWT', :git => 'https://github.com/yourkarma/JWT.git', :branch => 'master'
  pod 'OpenSSL', '~> 1.0'
end
